CREATE SCHEMA IF NOT EXISTS MYBOOKS;
use MYBOOKS;

CREATE TABLE IF NOT EXISTS MYBOOKS.BILLING_INFO(
ID INT PRIMARY KEY AUTO_INCREMENT,
ADDRESS VARCHAR(128) ,
CARD_TYPE VARCHAR(32) ,
CARD_NAME VARCHAR(32) ,
ACCOUNT_NR VARCHAR(64)

);
CREATE TABLE IF NOT EXISTS MYBOOKS.TASKS (
    id   INT PRIMARY KEY AUTO_INCREMENT,
    TASK_NAME VARCHAR(128) ,
    TASK_DESC VARCHAR(256),
    TASK_FILE CLOB(5K),
    USER_ID INT
);

CREATE TABLE IF NOT EXISTS MYBOOKS.USERS (
    id   INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL,
    email VARCHAR(128) NOT NULL,
    BIL_INFO_ID INT
);
ALTER TABLE MYBOOKS.USERS ADD FOREIGN KEY (BIL_INFO_ID) REFERENCES MYBOOKS.BILLING_INFO(ID);
ALTER TABLE MYBOOKS.TASKS ADD FOREIGN KEY (USER_ID) REFERENCES MYBOOKS.USERS(ID);
--INSERT INTO MYBOOKS.country (id,name) VALUES (1,'India');